export const ROLES = {
  ADMIN: "Admin",
  PROJECT_MANAGER: "Project Manager",
  ANALYST: "Analyst",
  EXECUTIVE_REVIEWER: "Executive Reviewer",
};

export const ROLE_LIST = Object.values(ROLES);

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  PROJECTS_READ: "projects.read",
  PROJECTS_WRITE: "projects.write",
  ALERTS_READ: "alerts.read",
  ALERTS_WRITE: "alerts.write",
  VENDORS_READ: "vendors.read",
  VENDORS_WRITE: "vendors.write",
  REPORTS_READ: "reports.read",
  REPORTS_WRITE: "reports.write",
  SIMULATIONS_READ: "simulations.read",
  SIMULATIONS_WRITE: "simulations.write",
  ML_PREDICT: "ml.predict",
  ML_TRAIN: "ml.train",
  WORKSPACE_READ: "workspace.read",
  WORKSPACE_MANAGE: "workspace.manage",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PROJECT_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.ALERTS_WRITE,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.VENDORS_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_WRITE,
    PERMISSIONS.SIMULATIONS_READ,
    PERMISSIONS.SIMULATIONS_WRITE,
    PERMISSIONS.ML_PREDICT,
    PERMISSIONS.WORKSPACE_READ,
  ],
  [ROLES.ANALYST]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.ALERTS_WRITE,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_WRITE,
    PERMISSIONS.SIMULATIONS_READ,
    PERMISSIONS.SIMULATIONS_WRITE,
    PERMISSIONS.ML_PREDICT,
    PERMISSIONS.WORKSPACE_READ,
  ],
  [ROLES.EXECUTIVE_REVIEWER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SIMULATIONS_READ,
    PERMISSIONS.ML_PREDICT,
    PERMISSIONS.WORKSPACE_READ,
  ],
};

export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}
